.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH LSS 1 "AUGUST 2012" Linux "User Manuals"
.SH NAME
lss \- The OpenLSS package manager
.SH SYNOPSIS
.B lss 
.I [-hyvUuSlb] 
.I [-irp <pkg>] 
.I [-s <keywords>] 
.I [-t <target>] 
.I [-m <mirror>]
.B ...
.SH DESCRIPTION
.B lss
manages the local package database for a target that is
running the OpenLSS framework.
.SH OPTIONS
.IP "-h --help"
Display help information
.IP "-y --yes"
Answer yes to all confirmation prompts
.IP "-v --verbose"
Increase verbosity and show underlying system commands
.SH RUN-TIME SETTINGS
.IP "-t --target <tgt>"
Manually specify the target (this should be set into the respective def)
.IP "-m --mirror <mirror>"
Specify external mirror (mainly for dev functions)
.SH PACKAGE MANAGEMENT
.IP "-U --update"
Syncs the local package database with the upstream
.IP "-s --search <keywords>"
Search the package database
.IP "-u --upgrade"
Upgrade the existing target
.IP "-i --install <packages>"
Install packages, can be a CSV of packages.
.IP "-r --remove <packages>"
Remove packages, can be a CSV of packages.
.IP "-p --purge <packages>"
Purge packages, like remove but processes additional removal hooks. Can be a CSV.
.SH LOCAL DB
.IP "--show-db"
Shows the local package db.
.IP "--db-file <file>"
When used with --show-db will show contents of a non standard package DB
.IP "-l --list"
List locally installed packages
.SH UTILITY
.IP "--int-version <version>"
Show the integer version of a standard version
.IP "--clear-cache"
Clear the local cache (must update db afterwards)
.SH DEV
.IP "-b --build-db"
Builds the package database from a local tree.
.IP "--export-db"
Export the package database to the remote mirror. (requires --mirror)
.SH SETTINGS
.IP "--set=::<usr|tgt>"
Set a setting value for the respective def (usr|tgt options, defaults to sys)
.IP "--add=::<usr|tgt>"
Add a value to an array for a respective def
.IP "--del=::<usr|tgt>"
Removes a value from an array for a respective def
.IP "--name <name>"
Name of the value to be modified
.IP "--value <value>"
Value to be set
.SH EXAMPLES
.IP "Update Package Database"
lss --update
.IP "Install Packages"
lss --install web,admin,staff
.IP "Remove Package"
lss --remove web
.IP "Purge Packages"
lss --purge staff,admin
.IP "Add Mirror to User Def"
lss --add=user --name mirror --value http://mirror.openlss.org
.IP "Add Restricted Mirror to Target Def"
lss --add=target --name mirrorauth --mirror http://private.openlss.org --value username:password
.IP "Change Default Target"
lss --set --name target --value /opt/lss
.IP "Change Default UI to Menu"
lss --set --name ui --value 1
.SH FILES
.I /usr/lss/users/<user>.lss
.RS
Storage of user settings
.RE
.SH BUGS
Report bugs at http://bugs.openlss.org
.SH AUTHOR
Bryan Tong <contact@nullivex.com> Tony Butler <spudz76@gmail.com>
